[
    {field:'ck',checkbox:'true'},
    {field:'busi_date',name:'业务日期',ctrlType:'easyui-datebox',hidden:false},
    {field:'create_time',name:'创建时间',ctrlType:'easyui-datetimebox',hidden:false,sortable:true},
    {field:'update_time',name:'操作时间',ctrlType:'easyui-datetimebox',hidden:false},
    {field:'big_area_name',name:'大区',ctrlType:'easyui-validatebox',hidden:false},
    {field:'area_name',name:'小区',ctrlType:'easyui-validatebox',hidden:false},
    {field:'org_name',name:'部门',ctrlType:'easyui-validatebox',hidden:false,sortable:true},
    {field:'outpay_org_name',name:'付款部门',ctrlType:'easyui-validatebox',hidden:false,sortable:true},
    {field:'doc_id',name:'应付单号',ctrlType:'easyui-validatebox',hidden:false},
    {field:'customer_name',name:'客户名称',ctrlType:'easyui-validatebox',hidden:false},
    {field:'should_car_type_name',name:'应付单类型',ctrlType:'easyui-validatebox',hidden:false},
    {field:'outcost_settle_type_name',name:'结算方式',ctrlType:'easyui-validatebox',hidden:false},
    {field:'should_amt',name:'总金额',ctrlType:'easyui-numberbox',hidden:false,precision:2,sortable:true,sorter:numberSort},
    {field:'real_amt',name:'已核销金额',ctrlType:'easyui-numberbox',hidden:false,precision:2},
    {field:'bal_amount',name:'未核销金额',ctrlType:'easyui-numberbox',hidden:false,precision:2},
    {field:'car_amt',name:'车价',ctrlType:'easyui-numberbox',hidden:false,precision:2},
    {field:'amount_under_approval',name:'审批中金额',ctrlType:'easyui-numberbox',hidden:false,precision:2,sortable:true,sorter:numberSort},
    {field:'payment_all_amount',name:'待申请金额',ctrlType:'easyui-numberbox',hidden:false,editor: {type: 'numberbox', options: {precision: 2}}},
    {field:'reward_amt',name:'奖励金额',ctrlType:'easyui-numberbox',hidden:false,precision:2},
    {field:'punish_amt',name:'罚款金额',ctrlType:'easyui-numberbox',hidden:false,precision:2},
    {field:'reduct_amt',name:'减免金额',ctrlType:'easyui-numberbox',hidden:false,precision:2},
    //件数，重量，体积，吨单价，方单价
    {field:'cust_goods_count',name:'件数',ctrlType:'easyui-numberbox',hidden:false,precision:0},
    {field:'cust_goods_weight',name:'重量',ctrlType:'easyui-numberbox',hidden:false,precision:2},
    {field:'cust_goods_volume',name:'体积',ctrlType:'easyui-numberbox',hidden:false,precision:3},
    {field:'cust_weight_per',name:'吨单价',ctrlType:'easyui-numberbox',hidden:false,precision:2},
    {field:'cust_vol_per',name:'方单价',ctrlType:'easyui-numberbox',hidden:false,precision:2},

    // {field:'payment_all_amount',name:'待申请金额',ctrlType:'easyui-numberbox',hidden:false},
    {field:'vehicle_law_id',name:'车号',ctrlType:'easyui-combobox',hidden:false},
    {field:'plan_reach_orgid_name',name:'下一站',ctrlType:'easyui-validatebox',hidden:false},
    {field:'handover_type_name',name:'交接类型',ctrlType:'easyui-validatebox',hidden:false},
    {field:'book_doc_status_name',name:'车辆状态',ctrlType:'easyui-validatebox',hidden:false},
    {field:'book_big_area_name', name: '装车部门大区', ctrlType: 'easyui-validatebox', hidden: false},
    {field:'book_little_area_name', name: '装车部门小区', ctrlType: 'easyui-validatebox', hidden: false},
    {field:'book_org_name', name: '装车部门', ctrlType: 'easyui-validatebox', hidden: false}
]