[
    {field:'ck',checkbox:true},
    {field:'doc_id',name:'交接单号',ctrlType:'easyui-validatebox',hidden:false},
    {field:'trans_doc_id',name:'调度单号',ctrlType:'easyui-validatebox',hidden:false},
    {field:'vehicle_law_id',name:'车牌号/车厢号',ctrlType:'easyui-validatebox',hidden:false,width:0.06},
    {field:'virtual_flag_name',name:'是否对装',ctrlType:'easyui-validatebox',hidden:false,width:0.05},
    {field:'box_asset_num',name:'甩箱资产编码',ctrlType:'easyui-validatebox',hidden:false,width:0.1},
    {field:'trans_way_name',name:'运输方式',ctrlType:'easyui-validatebox',hidden:false,width:0.05,styler:cellTrainStyler},
    {field:'stock_pos_id',name:'库位',ctrlType:'easyui-validatebox',hidden:false,width:0.05,styler:cellTrainStyler},
    {field:'book_org_id_name',name:'装车部门',ctrlType:'easyui-validatebox',hidden:false,styler:cellTrainStyler},
    {field:'plan_reach_orgid_name',name:'到达部门',ctrlType:'easyui-validatebox',hidden:false,styler:cellTrainStyler},
    {field:'book_doc_status_name',name:'状态',ctrlType:'easyui-validatebox',hidden:false,width:0.05},
    {field:'load_date',name:'装车日期',ctrlType:'easyui-datebox',hidden:false,width:0.06},
    {field:'send_time',name:'发车时间',ctrlType:'easyui-datetimebox',hidden:false,},
    {field:'arrive_time',name:'到达时间',ctrlType:'easyui-datetimebox',hidden:false,},
    {field:'resp_person_one_name',name:'负责人',ctrlType:'easyui-validatebox',hidden:false,width:0.05},
    {field:'resp_person_two_name',name:'二级负责人',ctrlType:'easyui-validatebox',hidden:false,width:0.05},
    {field:'in_time',name:'入库时间',ctrlType:'easyui-datetimebox',hidden:false,},
    {field:'unload_start',name:'卸车开始时间',ctrlType:'easyui-datetimebox',hidden:false,},
    {field:'unload_end',name:'卸车结束时间',ctrlType:'easyui-datetimebox',hidden:false,},
    {field:'vehicle_type_name',name:'车型',ctrlType:'easyui-validatebox',hidden:false,width:0.05},
    {field:'driver_name',name:'司机姓名',ctrlType:'easyui-validatebox',hidden:false,width:0.05},
    {field:'resp_mobile',name:'联系方式/大票号',ctrlType:'easyui-validatebox',hidden:false,},
    {field:'net_weight',name:'净重',ctrlType:'easyui-validatebox',hidden:false,width:0.05},
    {field:'net_volume',name:'净空',ctrlType:'easyui-validatebox',hidden:false,width:0.05},
    {field:'goods_nums',name:'交接票数',ctrlType:'easyui-numberbox',hidden:false,width:0.05},
    {field:'goods_count',name:'交接总件数',ctrlType:'easyui-numberbox',hidden:false,width:0.05},
    {field:'goods_weight',name:'交接总重量(kg)',ctrlType:'easyui-numberbox',hidden:false,width:0.06},
    {field:'goods_cube',name:'交接总体积(m³)',ctrlType:'easyui-numberbox',hidden:false,width:0.06},
    {field:'report_weight',name:'上报重量',ctrlType:'easyui-numberbox',hidden:false,width:0.05},
    {field:'car_price',name:'车价',ctrlType:'easyui-validatebox',hidden:false,width:0.05},
    {field:'prepay_amt',name:'始发预付款',ctrlType:'easyui-validatebox',hidden:false,width:0.05},
    {field:'trans_type_name',name:'交接类型',ctrlType:'easyui-validatebox',hidden:false,width:0.05},
    {field:'handling_type_name',name:'装卸类型',ctrlType:'easyui-validatebox',hidden:false,width:0.05},
    {field:'load_person',name:'货区管理员',ctrlType:'easyui-validatebox',hidden:false},
    {field:'unforklift_driver',name:'叉车司机',ctrlType:'easyui-validatebox',hidden:false},
    {field:'unhandling_person',name:'装卸人员',ctrlType:'easyui-validatebox',hidden:false},
    {field:'unhand_remark',name:'备注',ctrlType:'easyui-validatebox',hidden:false,width:0.2},
    {field:'remark',name:'交接备注',ctrlType:'easyui-validatebox',width:0.2,hidden:false},
    {field:'seal_count',name:'封签数量',ctrlType:'easyui-validatebox',hidden:false,width:0.05},
    {field:'seal_id_new',name:'封签明细',ctrlType:'easyui-validatebox',hidden:false},
    {field:'seal_check_result',name:'封签校验结果',ctrlType:'easyui-validatebox',hidden:false,},
    {field:'seal_check_remark',name:'封签校验备注',ctrlType:'easyui-validatebox',hidden:false,},
    {field:'seal_check_user',name:'封签校验人',ctrlType:'easyui-validatebox',hidden:false,width:0.05},
    {field:'expect_arrive_time',name:'预期到达时间',ctrlType:'easyui-datetimebox',hidden:false},

    // {field:'prepay_amt',name:'始发预付款',ctrlType:'easyui-validatebox',hidden:true},
    {field:'arrive_amt',name:'终到付款',ctrlType:'easyui-validatebox',hidden:true},
    {field:'back_amt',name:'始发回单付',ctrlType:'easyui-validatebox',hidden:true},


    {field:'trans_way',name:'运输方式id',ctrlType:'easyui-validatebox',hidden:true},
    {field:'vehicle_type',name:'车型id',ctrlType:'easyui-validatebox',hidden:true},
    {field:'train_flag',name:'铁路预约',ctrlType:'easyui-validatebox',hidden:true},

    {field:'container_num',name:'集装箱号',ctrlType:'easyui-validatebox',hidden:false,width:0.08},
    {field:'train_no',name:'铁路运号',ctrlType:'easyui-validatebox',hidden:false,width:0.08},
    {field:'pack_container_type',name:'装箱运输性质',ctrlType:'easyui-validatebox',hidden:false,width:0.08},
    {field:'recv_name',name:'收货人',ctrlType:'easyui-validatebox',hidden:false,width:0.06},
    {field:'recv_phone_no',name:'收货人电话',ctrlType:'easyui-validatebox',hidden:false,width:0.08},
    {field:'recv_address',name:'收货人地址',ctrlType:'easyui-validatebox',hidden:false,width:0.12},
    {field:'train_station_name',name:'到站火车站',ctrlType:'easyui-validatebox',hidden:false,width:0.08},

]